server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:file:./db/money
    driverClassName: org.h2.Driver
    username: tt
    password: tt
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
      use-new-id-generator-mappings: true
  h2:
    console:
      enabled: true